### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by karimcitoh** [bji/libs3#2]
Hello Bji,

Thanks for sharing libs3 with us. I want to ask you something.
I am using Mac OS and trying to install libs3, but I get all the time this error so I can't continue

```
In file included from src/acl.c:30:
inc/request.h:131:14: error: sizeof on pointer operation will return size of
      'char *' instead of 'char [9]' [-Werror,-Wsizeof-array-decay]
    char uri[MAX_URI_SIZE + 1];
             ^~~~~~~~~~~~
inc/util.h:61:51: note: expanded from macro 'MAX_URI_SIZE'
     MAX_URLENCODED_KEY_SIZE + (sizeof("?torrent" - 1)) + 1)
                                       ~~~~~~~~~~ ^
1 error generated.
make: *** [build/obj/acl.do] Error 1
```

Do you know how can I solve it?
Thanks in advance for your help,
best regards,
Karim

**Comment by mutantkeyboard** [comment]
@karimcitoh wow. 3 years and nobody answered. 
The fix is straightforward.
- Edit the GNUmakefile.osx CFLAGS
- Remove -Werror and add -Wunused-parameter instead
Then say it like
`make -f GNUmakefile.osx install` , and if it doesn't work install gnumake from Homebrew like
`brew install gnumake`, and then replace the upper command with gnumake so it looks like: 
`gnumake -f GNUmakefile.osx install`
